server:
  port: 8083

#Redis Properties
spring:
  cache:
    type: redis
    host: localhost
    port: 6379
    cache-names: product
    time-to-live: 600000

#MongoDb Properties
  data:
    mongodb:
      host: localhost
      port: 27017

logging:
  level:
    root: INFO